=== k4a-l/moe-equipment-simulator/assets/schemas/shields.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "array",
	"items": {
		"type": "object",
		"properties": {
			"id": {
				"type": "number"
			},
			"name": {
				"type": "string"
			},
			"description": {
				"type": "string"
			},
			"specials": {
				"type": "array",
				"items": {
					"type": "string"
				}
			},
			"buff": {
				"type": "string"
			},
			"effects": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"subject": {
							"type": "string",
							"enum": [
								"攻撃力",
								"命中",
								"物理与ダメージ",
								"魔法与ダメージ",
								"魔法ディレイ",
								"クリティカル率",
								"魔力",
								"攻撃ディレイ",
								"最大HP",
								"最大MP",
								"最大ST",
								"防御力",
								"回避",
								"素手",
								"刀剣",
								"こんぼう",
								"槍",
								"銃器",
								"弓",
								"盾",
								"投げ",
								"牙",
								"罠",
								"キック",
								"戦闘技術",
								"酩酊",
								"物まね",
								"調教",
								"破壊",
								"回復",
								"神秘",
								"召喚",
								"強化",
								"死魔",
								"魔法熟練",
								"自然調和",
								"暗黒命令",
								"取引",
								"シャウト",
								"音楽",
								"盗み",
								"ギャンブル",
								"パフォーマンス",
								"ダンス",
								"ペット経験値",
								"火属性効果",
								"水属性効果",
								"土属性効果",
								"風属性効果",
								"無属性効果",
								"HP自然回復",
								"ST自然回復",
								"MP自然回復",
								"移動速度",
								"水中速度",
								"耐全属性",
								"耐火属性",
								"耐水属性",
								"耐地属性",
								"耐風属性",
								"耐無属性",
								"SEEING",
								"HEARING",
								"SMELLING",
								"最大重量",
								"所持重量",
								"ジャンプ力",
								"BREATH",
								"料理ゲージ滑り",
								"料理ゲージ速度",
								"料理ヒットゾーン",
								"料理グレードゾーン",
								"料理マスターグレードゾーン",
								"鍛冶ゲージ滑り",
								"鍛冶ゲージ速度",
								"鍛冶ヒットゾーン",
								"鍛冶グレードゾーン",
								"鍛冶マスターグレードゾーン",
								"醸造ゲージ滑り",
								"醸造ゲージ速度",
								"醸造ヒットゾーン",
								"醸造グレードゾーン",
								"醸造マスターグレードゾーン",
								"大工ゲージ滑り",
								"大工ゲージ速度",
								"大工ヒットゾーン",
								"大工グレードゾーン",
								"大工マスターグレードゾーン",
								"裁縫ゲージ滑り",
								"裁縫ゲージ速度",
								"裁縫ヒットゾーン",
								"裁縫グレードゾーン",
								"裁縫マスターグレードゾーン",
								"薬調合ゲージ滑り",
								"薬調合ゲージ速度",
								"薬調合ヒットゾーン",
								"薬調合グレードゾーン",
								"薬調合マスターグレードゾーン",
								"装飾細工ゲージ滑り",
								"装飾細工ゲージ速度",
								"装飾細工ヒットゾーン",
								"装飾細工グレードゾーン",
								"装飾細工マスターグレードゾーン",
								"複製ゲージ滑り",
								"複製ゲージ速度",
								"複製ヒットゾーン",
								"複製グレードゾーン",
								"複製マスターグレードゾーン",
								"栽培ゲージ滑り",
								"栽培ゲージ速度",
								"栽培ヒットゾーン",
								"栽培グレードゾーン",
								"栽培マスターグレードゾーン",
								"美容ゲージ滑り",
								"美容ゲージ速度",
								"美容ヒットゾーン",
								"美容グレードゾーン",
								"美容マスターグレードゾーン",
								"キック命中率補正",
								"キック攻撃力補正",
								"釣りゲージ速度",
								"釣りヒットゾーン",
								"釣りゲージ長",
								"泳ぎ速度",
								"牙命中率補正",
								"牙攻撃補正",
								"盗み補正",
								"潤喉度",
								"満腹度",
								"ピッキング失敗回数補正",
								"ピッキング回転速度補正"
							]
						},
						"value": {
							"type": "number"
						}
					},
					"required": ["subject", "value"],
					"additionalProperties": false
				}
			},
			"genderAvailable": {
				"type": "string",
				"enum": ["男", "女", "ALL"]
			},
			"tribeAvailable": {
				"type": "string",
				"enum": ["パンデモス", "ニューター", "エルモニー", "コグニート", "ALL"]
			},
			"shipAvailable": {
				"type": "string"
			},
			"type": {
				"type": "string",
				"const": "shields"
			},
			"part": {
				"type": "string",
				"enum": ["右手", "左手"]
			},
			"armorClass": {
				"type": "number"
			},
			"skills": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"weapon": {
							"type": "string",
							"const": "盾"
						},
						"value": {
							"type": "number"
						}
					},
					"required": ["weapon", "value"],
					"additionalProperties": false
				}
			},
			"avoidance": {
				"type": "number"
			}
		},
		"required": [
			"id",
			"name",
			"description",
			"specials",
			"effects",
			"genderAvailable",
			"tribeAvailable",
			"shipAvailable",
			"type",
			"part",
			"armorClass",
			"skills",
			"avoidance"
		],
		"additionalProperties": false
	}
}

=== k4a-l/moe-equipment-simulator/assets/shields.json
[
	{
		"id": 595,
		"name": "ウッド バックラー",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "円形の木製盾\n小型で軽く　初心者でも扱いやすい",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 0.8,
		"avoidance": 45,
		"skills": [{ "weapon": "盾", "value": 1 }]
	},
	{
		"id": 601,
		"name": "トレント バックラー",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "円形のトレント製盾\n小型で軽く　初心者でも扱いやすい",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [
			{ "subject": "耐無属性", "value": 2 },
			{ "subject": "耐火属性", "value": 2 },
			{ "subject": "耐水属性", "value": 2 },
			{ "subject": "耐風属性", "value": 2 },
			{ "subject": "耐地属性", "value": 2 }
		],
		"type": "shields",
		"part": "左手",
		"armorClass": 1,
		"avoidance": 45,
		"skills": [{ "weapon": "盾", "value": 1 }]
	},
	{
		"id": 602,
		"name": "レザー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "柔らかい皮で作られた盾\n小型で軽く　初心者でも扱いやすい",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 1.7,
		"avoidance": 35,
		"skills": [{ "weapon": "盾", "value": 11 }]
	},
	{
		"id": 605,
		"name": "ドラゴン シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "ドラゴンの皮で作られた盾\n小型で軽量だが非常に高い防御力を誇る",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [{ "subject": "耐火属性", "value": 5 }],
		"type": "shields",
		"part": "左手",
		"armorClass": 3,
		"avoidance": 35,
		"skills": [{ "weapon": "盾", "value": 16 }]
	},
	{
		"id": 607,
		"name": "カッパー カイト シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "銅製の盾\n特殊なデザインが施されている\n耐久性に優れる",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 3.9,
		"avoidance": 25,
		"skills": [{ "weapon": "盾", "value": 31 }]
	},
	{
		"id": 608,
		"name": "ブロンズ カイト シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "青銅製の盾\n特殊なデザインが施されている",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 4.3,
		"avoidance": 25,
		"skills": [{ "weapon": "盾", "value": 31 }]
	},
	{
		"id": 609,
		"name": "アイアン カイト シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "鉄製の盾\n特殊なデザインが施されている",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 4.5,
		"avoidance": 25,
		"skills": [{ "weapon": "盾", "value": 31 }]
	},
	{
		"id": 610,
		"name": "スチール カイト シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "鋼鉄製の盾\n特殊なデザインが施されている",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 4.9,
		"avoidance": 25,
		"skills": [{ "weapon": "盾", "value": 31 }]
	},
	{
		"id": 611,
		"name": "シルバー カイト シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "銀製の盾\n特殊なデザインが施されている\nアンデッド系に有効",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 4.6,
		"avoidance": 25,
		"skills": [{ "weapon": "盾", "value": 31 }]
	},
	{
		"id": 612,
		"name": "ゴールド カイト シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "金製の盾\n特殊なデザインが施されている",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [{ "subject": "最大HP", "value": 1 }],
		"type": "shields",
		"part": "左手",
		"armorClass": 4.8,
		"avoidance": 25,
		"skills": [{ "weapon": "盾", "value": 31 }]
	},
	{
		"id": 614,
		"name": "ミスリル カイト シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "ミスリル製の盾\n特殊なデザインが施されている",
		"buff": "",
		"specials": ["強化可能", "生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 4.7,
		"avoidance": 25,
		"skills": [{ "weapon": "盾", "value": 31 }]
	},
	{
		"id": 615,
		"name": "オリハルコン カイト シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "オリハルコン製の盾\n特殊なデザインが施されている",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [{ "subject": "攻撃力", "value": 1 }],
		"type": "shields",
		"part": "左手",
		"armorClass": 6,
		"avoidance": 25,
		"skills": [{ "weapon": "盾", "value": 31 }]
	},
	{
		"id": 617,
		"name": "カッパー タワー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "銅製の長盾\n完全回避率とダメージ軽減のバランスが良い\n耐久性に優れる",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 6.5,
		"avoidance": 15,
		"skills": [{ "weapon": "盾", "value": 51 }]
	},
	{
		"id": 618,
		"name": "ブロンズ タワー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "青銅製の長盾\n完全回避率とダメージ軽減のバランスが良い",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 6.8,
		"avoidance": 15,
		"skills": [{ "weapon": "盾", "value": 51 }]
	},
	{
		"id": 619,
		"name": "アイアン タワー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "鉄製の長盾\n完全回避率とダメージ軽減のバランスが良い",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 7.1,
		"avoidance": 15,
		"skills": [{ "weapon": "盾", "value": 51 }]
	},
	{
		"id": 620,
		"name": "スチール タワー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "鋼鉄製の長盾\n完全回避率とダメージ軽減のバランスが良い",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 7.4,
		"avoidance": 15,
		"skills": [{ "weapon": "盾", "value": 51 }]
	},
	{
		"id": 621,
		"name": "シルバー タワー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "銀製の長盾\n完全回避率とダメージ軽減のバランスが良い\nアンデッド系に有効",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 7.2,
		"avoidance": 15,
		"skills": [{ "weapon": "盾", "value": 51 }]
	},
	{
		"id": 622,
		"name": "ゴールド タワー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "金製の長盾\n完全回避率とダメージ軽減のバランスが良い",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [{ "subject": "最大HP", "value": 1 }],
		"type": "shields",
		"part": "左手",
		"armorClass": 7.3,
		"avoidance": 15,
		"skills": [{ "weapon": "盾", "value": 51 }]
	},
	{
		"id": 624,
		"name": "ミスリル タワー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "ミスリル製の長盾\n完全回避率とダメージ軽減のバランスが良い",
		"buff": "",
		"specials": ["強化可能", "生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 7.3,
		"avoidance": 15,
		"skills": [{ "weapon": "盾", "value": 51 }]
	},
	{
		"id": 625,
		"name": "オリハルコン タワー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "オリハルコン製の長盾\n完全回避率とダメージ軽減のバランスが良い",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [{ "subject": "攻撃力", "value": 1 }],
		"type": "shields",
		"part": "左手",
		"armorClass": 8.6,
		"avoidance": 15,
		"skills": [{ "weapon": "盾", "value": 51 }]
	},
	{
		"id": 627,
		"name": "カッパー ウォー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "銅製の盾\n体を覆い隠すほどの大きさがある\n耐久性に優れる",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 9.9,
		"avoidance": 5,
		"skills": [{ "weapon": "盾", "value": 71 }]
	},
	{
		"id": 628,
		"name": "ブロンズ ウォー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "青銅製の盾\n体を覆い隠すほどの大きさがある",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 10.3,
		"avoidance": 5,
		"skills": [{ "weapon": "盾", "value": 71 }]
	},
	{
		"id": 629,
		"name": "アイアン ウォー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "鉄製の盾\n体を覆い隠すほどの大きさがある",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 10.5,
		"avoidance": 5,
		"skills": [{ "weapon": "盾", "value": 71 }]
	},
	{
		"id": 630,
		"name": "シルバー ウォー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "銀製の盾\n体を覆い隠すほどの大きさがある\nアンデッド系に有効",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 10.6,
		"avoidance": 5,
		"skills": [{ "weapon": "盾", "value": 71 }]
	},
	{
		"id": 631,
		"name": "ゴールド ウォー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "金製の盾\n体を覆い隠すほどの大きさがある",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [{ "subject": "最大HP", "value": 1 }],
		"type": "shields",
		"part": "左手",
		"armorClass": 10.8,
		"avoidance": 5,
		"skills": [{ "weapon": "盾", "value": 71 }]
	},
	{
		"id": 632,
		"name": "スチール ウォー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "鋼鉄製の盾\n体を覆い隠すほどの大きさがある",
		"buff": "",
		"specials": ["生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 10.9,
		"avoidance": 5,
		"skills": [{ "weapon": "盾", "value": 71 }]
	},
	{
		"id": 634,
		"name": "ミスリル ウォー シールド",
		"tribeAvailable": "ALL",
		"genderAvailable": "ALL",
		"shipAvailable": "ALL",
		"description": "ミスリル製の盾\n体を覆い隠すほどの大きさがある",
		"buff": "",
		"specials": ["強化可能", "生産可能"],
		"effects": [],
		"type": "shields",
		"part": "左手",
		"armorClass": 10.7,
		"avoidance": 5,
		"skills": [{ "weapon": "盾", "value": 71 }]
	},
	{
		"id": 635,
		"name": "オリハルコン ウォー シールド",
		"tribeAvailable": "ALL",
